version: "3.9"

services:

  app:
    build: .
    container_name: boletas_app
    restart: always

    ports:
      - "10001:10000"

    environment:
      DATABASE_URL: postgresql://boletas_user:123456@postgres:5432/boletas_db

    depends_on:
      - postgres

    volumes:
      - ./output:/tmp/boletas_app

  postgres:
    image: postgres:16

    container_name: boletas_postgres

    restart: always

    environment:
      POSTGRES_USER: boletas_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: boletas_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: